# Generated by Django 5.1.4 on 2025-04-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(blank=True, db_column='homeworld', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='ex09.planets'),
        ),
    ]
