# Generated by Django 4.2 on 2025-04-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
